### ISSUE TITLE
Build error introduced in commit 004546b156e78779fc7a5e95107b727c01fd16e0

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [geodynamics/hc#1]
There seems to be a bug introduced in commit 004546b156e78779fc7a5e95107b727c01fd16e0. Building from the previous commit, 083866227646cf04c246bf7328fe06479ae956fb, works, but 004546b causes errors:

```
...
sh_exp.c: At top level:
sh_exp.c:225:10: error: conflicting types for 'sh_total_power'
 HC_CPREC sh_total_power(struct sh_lms *exp)
          ^
In file included from hc.h:436:0,
                 from sh_exp.c:12:
hc_auto_proto.h:181:8: note: previous declaration of 'sh_total_power' was here
 double sh_total_power(struct sh_lms *);
        ^
...
```

The full log can be seen at the CIG [Jenkins page](https://blofeld.geodynamics.org/view/2%20Support%20Libraries/job/HC/37/). It's being built on CentOS7 [64bit](https://blofeld.geodynamics.org/view/2%20Support%20Libraries/job/HC/37/tag_arch=64bit,tag_os=centos/) and Ubuntu 14.04 [64bit](https://blofeld.geodynamics.org/view/2%20Support%20Libraries/job/HC/37/tag_arch=64bit,tag_os=ubuntults/) and [32bit](https://blofeld.geodynamics.org/view/2%20Support%20Libraries/job/HC/37/tag_arch=32bit,tag_os=ubuntults/).

**Comment by thwbecker** [comment]
not sure why that doesn't work. works for me. default precision setting in
hc.h is

 HC_PRECISION 16

which sets

#define HC_PREC double

and then

#define HC_CPREC HC_PREC

unless HC_CPREC is defined elsewhere. then, the autoproto file should be
automatically generated after a make clean ; make

Thorsten W Becker - geodynamics.usc.edu
http://geodynamics.usc.edu/~becker/contact.html

**Comment by tjesser-ucdavis-edu** [comment]
Hmm, that's not the behavior I'm seeing.
Right now our Jenkins script does a git clean, then uses:

```
# centos GMT package is v5, so we use v4 artifacts copied into workspace
if [ $tag_os = 'centos' ]
then export GMTHOME="${WORKSPACE}/${ARTIFACT_GMT_SUBDIR}/${RESULT_SUBDIR}"
fi

if [ $tag_os = 'ubuntults' ]; then export GMTHOME="$UBUNTU_GMTHOME"; fi

make
```

I saw that you mentioned running `make clean` before `make` and when I added that, I got this error:

```
...
+ make clean
rm -f hc_auto_proto.h objects/*.o  objects/*.a bin/*
+ make
mkdir -p objects;
mkdir -p bin;
cproto   -DHC_PRECISION=32 -O2  -I.  -I/usr/lib/gmt/include -I/include   -DNO_RICK_FORTRAN    -I/usr/lib/gmt/include -I/include -DPREM_MODEL_FILE=\"prem/prem.dat\" -DGENERATE_PROTO  -f 2 -p *.c  | \
        grep -v "void main("  | \
        grep -v "ggrd_gt_bcr_init_loc(" | \
        grep -v "ggrd_grdtrack_interpolate(" | \
        grep -v "ggrd_grdtrack_init(" | \
    grep -v "int main(" > hc_auto_proto.h
/bin/sh: 1: cproto: not found
...
```

**Comment by thwbecker** [comment]
you'd need the cproto program installed to regenerate the automatic
prototype file. because of no everyone having it installed, the
hc_auto_proto file is part of the distro, and should normally match what's
produced by the default compile.

Thorsten W Becker - geodynamics.usc.edu
http://geodynamics.usc.edu/~becker/contact.html

**Comment by tjesser-ucdavis-edu** [comment]
Okay, is that something Jenkins should be using or should I just remove the `make clean`?

**Comment by tjesser-ucdavis-edu** [comment]
Either way, it doesn't sound like the initial problem will be solved, correct?

**Comment by thwbecker** [comment]
you could try to install cproto and then see if you can compile with make
clean; make

Thorsten W Becker - geodynamics.usc.edu
http://geodynamics.usc.edu/~becker/contact.html

**Comment by tjesser-ucdavis-edu** [comment]
Well, it looks like https://github.com/geodynamics/hc/commit/79efdfe7f05180c05f51d555b988834b1c2dafc3 fixed the issue, which is good because apparently CentOS7 doesn't have a cproto package. I removed `make clean` from the Jenkins script and it is now building from master `HEAD`.

Thanks for the help, I think this issue can be closed.

**Comment by thwbecker** [comment]
Okay

---

Thorsten W Becker - USC
